---

- name: install tools
  yum:
    name:
      - hdparm
      - htop
      - iftop
      - iotop
      - ipmitool
      - lm_sensors
      - nmap
      - nmap-ncat
      - python2-speedtest-cli
      - smartmontools
      - stress
      - upower
  become: true

- name: install s-tui
  pip:
    extra_args: --user
    name: s-tui
  become: true

- name: disable ipmievd
  tags: notest
  service:
    enabled: false
    name: ipmievd
    state: stopped
  become: true
